x-common-env-vars: &common-env-vars
  POSTGRES_SERVER: db
  POSTGRES_USER: deep
  POSTGRES_PASSWORD: opinion
  POSTGRES_DB: deep_ice
  REDIS_HOST: redis

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_ice_app
    ports:
      - "80:80"
    environment:
      <<: *common-env-vars
    depends_on:
      - alembic
      - worker

  db:
    image: postgres:latest
    container_name: deep_ice_db
    environment:
      <<: *common-env-vars
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_ice_alembic
    command: alembic upgrade head
    environment:
      <<: *common-env-vars
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: deep_ice_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_ice_worker
    command: arq deep_ice.TaskQueue
    environment:
      <<: *common-env-vars
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
