services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_ice_app
    ports:
      - "80:80"
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: opinion
      POSTGRES_DB: deep_ice
      REDIS_HOST: redis
    depends_on:
      - alembic
      - worker

  db:
    image: postgres:latest
    container_name: deep_ice_db
    environment:
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: opinion
      POSTGRES_DB: deep_ice
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  alembic:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: deep_ice_alembic
    command: uv run alembic upgrade head
    environment:
      POSTGRES_SERVER: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: deep
      POSTGRES_PASSWORD: opinion
      POSTGRES_DB: deep_ice
    depends_on:
      - db

  redis:
    image: redis:alpine
    container_name: deep_ice_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: uv run arq deep_ice.TaskQueue
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis

volumes:
  postgres_data:
  redis_data:
